### ISSUE TITLE
Yellow Blocks [Rewritten for AB+]

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#10]
TO DO
- [X] Code it
- [X] Test them
- [x] Upload to Repo

**Comment by dedChar** [comment]
@ProbablyTez I'll try out if the game allows me to actually split everything up into multiple lua files, if yes, I'll upload it to the repo, but seems like it's doable: (disregard the post title implying differently ^^) https://www.reddit.com/r/themoddingofisaac/comments/5m4nxm/psa_luas_require_is_fucked/

**Comment by ProbablyTez** [comment]
Yeah that'd be really useful if it were possible

**Comment by dedChar** [comment]
Turns out it only works with --luadebug set as a game flag right now, but like I said, nicalis is working on it :/
