### ISSUE TITLE
[Beggar] Treasure Hoarder

### ISSUE THREAD

**Issue by NotNeal** [ProbablyTez/Agony#101]
Acts similarly to other beggars, but is slightly more rare.

Takes a random passive item and pays out from this set;
(25%) 7 Random Consumables
(12.5%) 5 Random Trinkets
(12.5%) 5 Random Runes
(12.5%) 3 Random Chests
(12.5%) Random Stat Up
(6.25%) 1-2 Random Items (From an exclusive pool of new items maybe?) (Disappears)
(6.25%) 1-3 Random Devil/Angel Items (Disappears)
(6.25%) 2 Dimes
(6.25%) Nothing

It's sort of a very high risk/high reward version of the regular beggars.

Not sure if it's okay to randomly pop out of the blue to suggest something, (or if something like this is even possible considering the current state of the API,) but here it is either way :P

**Comment by dedChar** [comment]
Sounds like a good new mechanic to me! Thanks for the suggestion ^^
Though the percentages don't add up to 100...

**Comment by CrimsonCube** [comment]
My proposition for a name - Treasure Hoarder. It would fit with Key Master for example.

**Comment by dedChar** [comment]
I think Treasure Hoarder fits pretty good as a name

**Comment by NotNeal** [comment]
Made some slight changes to the probability to make them add up to 100, because I'm a dolt and forgot to do that.

**Comment by ProbablyTez** [comment]
I love the concept, great idea!
