### ISSUE TITLE
[Treasure Hoarder] Will not accept any modded item

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#106]
We can fix this if we know how many items are in Agony but it won't work with items from other mods

**Comment by dedChar** [comment]
Dang Tez, you're really pumping out commit after commit ^^

**Comment by dedChar** [comment]
I'm sorry that I can't help out as much as I'd want to because I'm a bit soaked in school stuff right now :/

**Comment by ProbablyTez** [comment]
Hey it's no worries, we've got plenty of time before release and you've already done a lot! ^^
