### ISSUE TITLE
[Passive] Pyamid Head

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#116]
Art
- [ ] Collectible Sprite
- [ ] Costume Sprite 
- [ ] Note Sprite
 

Side note : this is a reference to Silent Hill's Pyramid Head, the sprite should be similar to it

Idea card : #78

**Comment by VortexGames** [comment]
Should be devil pool exclusive. It alters the run to much to replace a treasure room item.

**Comment by ProbablyTez** [comment]
Polyphemus, mom's knife and Epic fetus are far more powerful and are treasure room too! Only the rarity matters for balance 😉
