### ISSUE TITLE
[Passive] Overgrown Spine

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#118]
Art
- [x] Collectible Sprite
- [x] Costume Sprite 
- [x] Note Sprite

Code
- [ ] change laser color

**Comment by ProbablyTez** [comment]
Aaaaaaaaand someone made a similar item almost exactly at the same time x)
https://gfycat.com/SplendidIcyFrogmouth

**Comment by dedChar** [comment]
Whoops xD

**Comment by mtblox** [comment]
http://i.imgur.com/FU4Lbdw.png
http://i.imgur.com/WUyfsAE.png
http://i.imgur.com/40YTzWT.png

Overgrown Spine sprites are done.
