### ISSUE TITLE
[Passive] Electric Hair

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#126]
Art
- [x] Collectible Sprite
- [x] Costume Sprite 
- [x] Note Sprite

**Comment by mtblox** [comment]
http://i.imgur.com/5EZhrgu.png
http://i.imgur.com/JrU0sHf.png
http://i.imgur.com/3F7lLUL.png
http://i.imgur.com/qZdCiHW.png

Electric Hair sprites are done. Inspiration was a Van de Graaff generator, blue spikes are static electricity that look like electrified hair. I made two costumes kinda lazily, one was a modified Wafer glow, and the other is just a line of the electric blue colour on top of Isaac's head, for an overlay.
