### ISSUE TITLE
[Passive] Til Death Do Us Apart

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#127]
### Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Costume Sprite?
### Code
- [x] Bug : #128

**Comment by mtblox** [comment]
http://i.imgur.com/YVGQiNz.png
http://i.imgur.com/v3WKVkH.png
http://i.imgur.com/UnkhnoU.png

TDDUA sprites are done.
