### ISSUE TITLE
[Little Sugar Dumdum] Using the item more than once per room fucks up stats

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#129]
All the saved stats will be overwritten with stats the player currently has, which are random because the item's effect is running. That way after leaving the room the player will have random stats.

Tbh I kinda want to leave this as a synergy with Car Battery :D
What do you think of this @ProbablyTez?

**Comment by ProbablyTez** [comment]
Actually yeah, that's a fun bug feature, I vote to keep it in!
