### ISSUE TITLE
[Passive] Pythagore's body

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#130]
Entities explode on death, this include monsters and friendly flies/spiders
Devil/Treasure pool

**Comment by ProbablyTez** [comment]
PS: Pythagore is the name of my cat, here's what he looks like
![image](https://cloud.githubusercontent.com/assets/15686741/22406098/6e7c2e26-e64c-11e6-8b81-22098ae14dae.png)

**Comment by dedChar** [comment]
Awww :3 Nice that you want to include your own cat into the game ^^

**Comment by ProbablyTez** [comment]
I'm just following ed's footsteps :D
