### ISSUE TITLE
[Familiar] Putrid baby

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#136]
Occasionally spawns friendly spiders

**Comment by dedChar** [comment]
Isn't that pretty much what Sissy Longlegs does?

**Comment by ProbablyTez** [comment]
Oh wait, yeah you're right

**Comment by ProbablyTez** [comment]
I got so used to Sissy Longlegs just being a cute familiar I forgot she actually did something

**Comment by dedChar** [comment]
Haha nice xD
