### ISSUE TITLE
[Passive] Yeux Revolver

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#146]
### Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Costume Sprite
### Code
- [x] Find a way to do the Vlambeer freeze upon hitting an enemy, may not be doable

Idea card : #131

**Comment by mtblox** [comment]
http://i.imgur.com/u2Z4Dq5.png
http://i.imgur.com/h5ebjLY.png
http://i.imgur.com/lJomEeM.png

Sprites are done.

**Comment by dedChar** [comment]
what do you mean with the vlambeer freeze?

**Comment by ProbablyTez** [comment]
Oh, I forgot I had to do this, you'll see (if I can make it work)
