### ISSUE TITLE
[Active] Brother Cancer

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#148]
### Tumor Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Costume Sprite
### Brother Cancer Art
- [x] Collectible Sprite
- [x] Note Sprite

Idea card : #141

**Comment by mtblox** [comment]
http://i.imgur.com/eFhP6FV.png
http://i.imgur.com/KItZROP.png

Sprites are done.
