### ISSUE TITLE
Ghastly Queen

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#16]
- Similar movements to the other Spider bosses
- Four attack patterns 
     - Jump
          - Invisible when jumping
          - Can go trough walls
          - If jumping trough a wall, reappear on the opposite wall (if leaving trough the left, appear trough the right)
     - Spawns ghost related entities
     - Screams, slowing the player if too close
     - Fires a Brimstone laser in a X laser
          - Can jump while doing this attack (may need to be tweaked to be avoidable)

**Comment by ProbablyTez** [comment]
The Haunt + The Wretched ? That could be fun

**Comment by dedChar** [comment]
I think you were the one who originally suggested this on trello :P
