### ISSUE TITLE
[Active] Matryoshkas

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#160]
- Big Babushka
   - d

**Comment by dedChar** [comment]
What grandmas are you talking about :D

**Comment by ProbablyTez** [comment]
This item isn't ready, I need to work some more on the design but I think you'll like it. The idea is, every time you use the item it breaks and reveal a smaller babushka, you know, thsese russian dolls

**Comment by dedChar** [comment]
Oh that's what you meant :P They are called Matryoshkas. Babushka means grandma xD

**Comment by ProbablyTez** [comment]
Right! I keep confusing the two x)
