### ISSUE TITLE
Eternals

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#17]
Eternals should be reworked using the lua engine, but also some sprites should be redone

### AI Rework
- [ ] Psy Tumor
- [ ] Tumor
- [x] Roundworm
- [ ] Nightcrawler
- [ ] Small Crazy Longlegs
- [ ] Small Baby Longlegs
- [ ] Crazy Longlegs
- [ ] Baby Longlegs
- [ ] Lil' Haunt
- [x] Dip
- [x] Squirt
- [ ] Dinga
- [ ] Half Sack
- [ ] Blubber
- [ ] Fat Sack
- [ ] Fatty
- [ ] Wizoob
- [ ] Ragling
- [ ] Pale Fatty

### Sprite Rework
Some of the sprites were done pretty lazily compared to others
- [x] Psy Tumor
- [ ] Small Baby Longlegs
- [ ] Ragling

**Comment by dedChar** [comment]
FireProjectiles() is broken rn meeeeeeeehhhh nicalis

**Comment by ProbablyTez** [comment]
Damn it, haven't messed around with tears yet, sucks if it's broken x)

**Comment by dedChar** [comment]
Here's a list of broken stuff right now    https://www.reddit.com/r/themoddingofisaac/comments/5mzkqp/afterbirth_lua_api_bug_megathread/

**Comment by dedChar** [comment]
@ProbablyTez What do you think of the idea that tears shot by eternals in their special eternal attacks should be white/greyish? Basically Hush's tears but in grey.

**Comment by ProbablyTez** [comment]
Oh yeah, that's a good idea ^^
It gives them more personality

**Comment by dedChar** [comment]
@ProbablyTez Eternal Roundworms: https://youtu.be/O3yoeaeBOnY

**Comment by ProbablyTez** [comment]
I love it! Excelllent work ^^

**Comment by dedChar** [comment]
They spawn automatically btw, so no need to create extra rooms with them anymore ^^
You can still spawn them through the room editor though if needed

**Comment by ProbablyTez** [comment]
Amazing, can't wait to randomly find them ^^

**Comment by PoiuyPL** [comment]
Eternal Psy Tumor texture
![monster_253_psytumer](https://cloud.githubusercontent.com/assets/18503542/22828749/4f15ae20-ef9f-11e6-8814-9bac4c02fc05.png)
