### ISSUE TITLE
[Familiar] Sack of Sacks of Sacks

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#172]
Has a chance to spawn a sack familiar at the beginning of each floor
Treasure and shop pool

**Comment by dedChar** [comment]
Wouldn't that just be Sack of Sacks though? :D

**Comment by ProbablyTez** [comment]
I thought sack of sacks spawned sack pickups

**Comment by ProbablyTez** [comment]
I'm talking about sack familiars here :p

**Comment by dedChar** [comment]
Yeah I got that ^^
Although you're right that "Sack of Sacks" sounds like a sack spawning sack pickups, to me "Sack of Sacks of Sacks" sounds like the Sack spawns Sacks that also spawn some kind of Sacks. :P

P.S: Sacks.

**Comment by dedChar** [comment]
The bomb and rune sack are called bags for some reason, what if we'd call it "Bag of Sacks" with the description "Or is it a Sack of Bags?.." ? ^^

**Comment by ProbablyTez** [comment]
But but but I wanted to go deeper into the sack of sack joke 😢

**Comment by dedChar** [comment]
Poor Tez, can't have his sack-ception jokes :(
We could actually make it spawn a sack that spawns sacks though
Just for the joke :D

**Comment by ProbablyTez** [comment]
I wanted it to be a little more interestign than a sack of sacks soawner tho 😄

**Comment by mtblox** [comment]
call it Sack Sack

**Comment by dedChar** [comment]
Not sure if "Sack Sack" would be to close to "Sack of Sacks" which apparently already exists... :/

**Comment by dedChar** [comment]
Sooo I've gone ahead and done this one ^^

I implemented it as two familiars: `Sack of Sacks of Sacks` and `Sack of Bags`. The first one, only spawns the `Sack of Bags` after a few rooms of picking it up. It spawns it only once. The `Sack of Bags` then spawns a random sack with a 50% chance and another `Sack of Bags` with a 1% chance when entering a new floor.

**Comment by ProbablyTez** [comment]
We're getting deep into the sackhole
