### ISSUE TITLE
[Passive] Fragile Conception

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#173]
### Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Costume Sprite

**Comment by mtblox** [comment]
http://i.imgur.com/YTPmMX1.png

**Comment by mtblox** [comment]
http://i.imgur.com/YTPmMX1.png
http://i.imgur.com/lhn4HCo.png
http://i.imgur.com/0T1EER2.png

sprites are done
