### ISSUE TITLE
[Passive] Dice Tattoo

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#174]
Upon clearing a room, rerolls a random Item on the player
Treasure Pool

**Comment by dedChar** [comment]
The name reminds me of swallowed penny...
What if it was a trinket and it would trigger upon taking damage instead?

**Comment by ProbablyTez** [comment]
Oooh, yeah, that's a great idea! We can do both actually!

**Comment by dedChar** [comment]
Haha I was thinking about turning this into a Dice Tatoo, too! :D

**Comment by ProbablyTez** [comment]
Hive mind!
