### ISSUE TITLE
[Trinket] Swallowed Dice

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#175]
Upon taking damage, rerolls a random item from the player

**Comment by dedChar** [comment]
This gets pretty close to the cracked dice trinket... Do you think we should still make this one then?

**Comment by ProbablyTez** [comment]
It's close but I think there's no overlap between the two trinkets, so worth making imo ^^

**Comment by dedChar** [comment]
Ok then ^^
