### ISSUE TITLE
[Passive] Electrode

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#176]
'Closed circuit'

Isaac's tears travel in an arc in front of him, firing out of his right eye and travelling around to his left eye.
Tears up (tear rate -5)
Damage down (-1 damage, x0.8)

**Comment by ProbablyTez** [comment]
I like the idea!

**Comment by mtblox** [comment]
http://i.imgur.com/qmJJCNi.png
http://i.imgur.com/42eHylh.png
http://i.imgur.com/ENyUHKq.png

Assets for the electrode are ready.
