### ISSUE TITLE
[Passive] Necrosis

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#178]
'Maggot-infested flesh'

When Isaac touches an enemy, he leaves maggots on them.
They slow the enemy down permanently, and the slow effect is more powerful the lower percentage of health they have.

**Comment by ProbablyTez** [comment]
> They slow the enemy down permanently, and the slow effect is more powerful the lower percentage of health they have.

I like this part, this could make a great item.  
Something like : Enemies speed are now proportional to their % of hp
