### ISSUE TITLE
[Passive] Marked Basalt

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#180]
'Hot rocks'

Tinted rocks and bomb rocks explode with a Mr. Mega explosion.
Bomb rocks drop items like tinted rocks do.
Found by bombing a tinted rock.

**Comment by ProbablyTez** [comment]
> Tinted rocks and bomb rocks explode with a Mr. Mega explosion.

I like the idea of making rocks do stuff they usually dont do

> Bomb rocks drop items like tinted rocks do.
> Found by bombing a tinted rock.

I think this part would be more fitting as a trinket
