### ISSUE TITLE
[Passive] Geode

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#181]
'A diamond in the rough'

Tinted rocks have a 66% chance to pay out with a pedestal item.
The tinted rock items pull from the item room pool.
Found by bombing a tinted rock.

**Comment by dedChar** [comment]
I like it, 66% sounds a bit high though. Maybe 33% or 25%?

**Comment by mtblox** [comment]
Yeah, that's fair enough, 25% will do.
