### ISSUE TITLE
[Active] The Fireplace

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#187]
One charge
Spawns a fireplace nearby
Treasure pool
May need a better name

**Comment by mtblox** [comment]
How about Firewood for a name?

And on top of that, how about a Charcoal trinket that increases the odds of items dropping from fires, just like petrified poop does?

**Comment by ProbablyTez** [comment]
The fires props in the game are called Fireplaces tho 😛 
And yeah, that's a nice idea for a trinket
