### ISSUE TITLE
[Active] Someone's Shoe

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#190]
Art
- [x] Collectible Sprite
- [x] Note Sprite

**Comment by mtblox** [comment]
http://i.imgur.com/9qpOQOA.png
http://i.imgur.com/43Shyv3.png

Someone's Shoe sprites are done.

**Comment by dedChar** [comment]
Nice! ^^
I sent you an invitation to the Team on Git so you can add changes to the repo directly :)
