### ISSUE TITLE
[Active] Thermostat

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#197]
'Colder... warmer...'

Has no charge time. Infinite uses.
When used, changes to one of three modes in a cycle: normal, hot and cold.
Normal doesn't do anything.
Hot makes Isaac and enemies move faster, enemies have the fire debuff for as long as the Thermostat remains in this mode.
Cold makes Isaac and enemies move slower, Isaac still shoots tears normally, enemy tears are slowed.

**Comment by dedChar** [comment]
Sounds nice!
But I think it would be better if it had a one room charge, maybe even with rechargability, because then one could not just always cycle to a specific state.

**Comment by ProbablyTez** [comment]
How about making the effect random, 50% chance to warm or cool things down

**Comment by mtblox** [comment]
Yeah sure, add a recharge time to it. Maybe around 8 seconds.
