### ISSUE TITLE
[Familiar] Tiny Tiny Horn

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#198]
### Art
- [ ] Sprites
   - [ ] FloatDown
   - [ ] FloatUp
   - [ ] FloatSide (facing to the right)
   - [ ] FloatShootDown
   - [ ] FloatShootUp
   - [ ] FloatShootSide (facing to the right)
- [ ] Animation
   - [ ] FloatShootDown
   - [ ] FloatShootUp
   - [ ] FloatShootSide (facing to the right)
- [ ] Collectible Sprite
- [ ] Note Sprite

The FloatShoot* Sprites and Animations should be similar to the one Little Horn does when he summons an orb. 

### Code
- [x] Bug: #199 
- [ ] When entering a fight with Little Horn, the familiar will switch sides and fight for Little Horn instead

Idea card : #83

**Comment by VortexGames** [comment]
Just call it Littlest Horn
