### ISSUE TITLE
[Tiny Tiny Horn] Floods the log

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#199]
It floods the log with the following:
`[INFO] - [warn] No OverlayEffect Null found for Entity Dark Ball with sprite gfx/404.001_DarkBall.anm2`
This has something to do with the fact that the orb is charmed, not sure how we'd fix this though.

**Comment by CrimsonCube** [comment]
Currently solved by adding EffectOverlay in anm2 file - note that now the charm effect is visible on the orb. If this is bad then reopen the issue.

**Comment by ProbablyTez** [comment]
Well that IS bad, it's a minor issue but still an issue

**Comment by dedChar** [comment]
no worries ^^ fixed that

**Comment by ProbablyTez** [comment]
Beautiful <3
