### ISSUE TITLE
[Passive] Jaundice

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#202]
'Yellow tears'

Boring one here, but Isaac has a chance to shoot yellow tears, like Number One.
The tears leave a Lemon Mishap pool where they land.
The chance to fire them maxes out at 25 luck.

**Comment by ProbablyTez** [comment]
Isnt that exactly Mysterious liquid but yellow ?

**Comment by mtblox** [comment]
Well, no, it starts off much larger, and it does a lot of damage. To counteract this, it is luck-based as to whether you shoot one or not. Mysterious Liquid has the potential to be improved, but only in a breaking run. It also makes use of the Lemon Mishap item, which has a good effect, but used in a terrible way.

**Comment by ProbablyTez** [comment]
Oh okay, so it's basically a mysterious liquid on Steroids, yeah I can dig that!
