### ISSUE TITLE
[Active] Worm Knot

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#206]
6 charge
Drops a random worm trinket on use
While held, if the player is holding a worm trinket, gives an all stat up 
Shop pool

**Comment by dedChar** [comment]
Hmm.. not sure. I don't really see the value of 15 coins in this item :/

**Comment by NotNeal** [comment]
Maybe make it boost the effect of worm trinkets similar to how mom's box boosts the effects of all trinkets? (Although mom's box also boosts the effects of some worm trinkets, so I dunno.)

**Comment by ProbablyTez** [comment]
What about this : Gives a boost of some kind depending on the worm tirnket you're holding
