### ISSUE TITLE
Bat Boss

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#21]
- Very slowly flies around
- immobile when attacking
- Three attack patterns
     - Opens its mouth, spawning random bat entities
     - Fires tears in a circle pattern, fires multiple volleys
     - Screams, confusing the player if he's too close
          - The confusion inverts the controls (up is down, left is right)

**Comment by dedChar** [comment]
I think it should definitely spawn some bats (maybe a special variant for that bossfight? maybe like the regular charging bats but smaller, cuter and less hp?) and they should fly out of the boss bat's mouth. 
And circle patterns of tears as an attack sound good too!

**Comment by ProbablyTez** [comment]
Oh yeah, I really like this idea, it opens its mouth really wide and lots of bats with less hp spawn
