### ISSUE TITLE
[Passive] Placeholder

### ISSUE THREAD

**Issue by NotNeal** [ProbablyTez/Agony#210]
- **Copies the latest passive item the player picks up**
- **Secret Pool**

**Comment by dedChar** [comment]
Oh wait do you mean the name 'Placeholder' literally? :D
Or is it just a placeholder?

**Comment by ProbablyTez** [comment]
It's a fun idea, but I think the placeholder sprite is going a bit too far haha
Unless they worked on Agony people won't get the reference ^^
