### ISSUE TITLE
[Passive] Sacramental Wine

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#214]
('HP down, spirit up'

All red hearts become blue hearts.
You gain a blue heart.
Also a tears up, because why not. Tear delay -2.

http://i.imgur.com/fcXSOFk.png
http://i.imgur.com/Y20WLzL.png
http://i.imgur.com/ueSDw3b.png)

- **Red Hearts heart containers are converted to blue hearts**
- **All red and black heart pickups are converted to blue hearts**
- **Damage Up**
- **Angel Pool**

**Comment by ProbablyTez** [comment]
Turned the tears into a damage up because Agony already has a low ratio of tears/damage up items
