### ISSUE TITLE
[Familiar] Sack of Sacks of Sacks

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#217]
### Art
- [x] Sack of Sacks of Sacks
   - [x] (Collectible) Sprite
   - [x] Death note Sprite
- [x] Sack of Bags
   - [x] (Collectible) Sprite
   - [x] Death note Sprite

Idea card : #172

**Comment by mtblox** [comment]
http://i.imgur.com/tF93TWi.png
Sack of Sacks of Sacks note sprite is done.

http://i.imgur.com/4CEoQB5.png
Sack of Bags note sprite is done.
