### ISSUE TITLE
[Trinket] Pocket Holes

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#222]
The player randomly drops a consumable (bomb, key or coin)

**Comment by dedChar** [comment]
Uuuhhhhhh, I really like this one ^^
Doesn't seem all that useful though I think :D

**Comment by ProbablyTez** [comment]
Well it's really useful if you have humbleing bundle, or any other duplicating trinket 😄 
Also, there's a small chance that your penny will turn into a dime so, yay!

And ofc, you can always reroll all your dropped consumables if you dont want them anymore 😛
