### ISSUE TITLE
[Familiar] Chest of Chests

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#223]
### Art
- [x] Collectible Sprite
- [x] Death note Sprite
- [x] Familiar Sprite
### Animation
- [x] Anims:
   - [x] Spawn
   - [x] FloatDown

Idea card : #88

**Comment by mtblox** [comment]
http://i.imgur.com/qM4eG2R.png
http://i.imgur.com/NNOKWKG.png

Sprites are done.

**Comment by dedChar** [comment]
I think it looks pretty boring floating behind the player being permanently open
It needs a closed state and then an opening animation when it spawns a chest

**Comment by mtblox** [comment]
http://i.imgur.com/Z4AFcHl.png

Done.
