### ISSUE TITLE
[Card] Reload!

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#224]
### Art
- [x] Card Sprite
### Code
- [x] Bug #261 
- [x] Add Big Card Animation

**Comment by mtblox** [comment]
http://i.imgur.com/Y9I0Mgz.png
http://i.imgur.com/y97VpWr.png

Not sure what you meant so I did a small card face and a big card overlay. Anyway, done.

**Comment by ProbablyTez** [comment]
We only needed the small one, but we can also make a big animation so yay, thanks!
