### ISSUE TITLE
[Passive] Spooderboi

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#225]
### Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Costume Sprite
### Code
- [x] Bug : #128 
### Design
- [x] Redesign the effect, I don't like it anymore.

Note: Costume should replace Isaac's legs with spider legs, because that's awesome

**Comment by mtblox** [comment]
http://i.imgur.com/fSlSaLo.png
http://i.imgur.com/rm1LikD.png
http://i.imgur.com/Ao3Foy3.png

Sprites are done, I am actually proud of this.
