### ISSUE TITLE
[Familiar] Grandpa Fly

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#226]
### Art
- [x] Sprites
   - [x] FloatIdle
   - [x] FloatSpawn
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Bug: #267 

### Code
- [x] Bug: #266 

Idea card : #158

**Comment by mtblox** [comment]
http://i.imgur.com/I4qzzOD.png
http://i.imgur.com/tJ4Kehj.png
http://i.imgur.com/pextH6B.png

Grandpa Fly sprites are done, spritesheet is a bit rough so it might need some adjusting. First two frames are idle, others are spawning.
