### ISSUE TITLE
Moter

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#235]
Splits into 4 Eternal Attack Fly on death

**Comment by CrimsonCube** [comment]
Partially done: Eternal Flies are not implemented yet, so for now it spawns normal Attack Flies.

**Comment by dedChar** [comment]
Just simply spawn them with a subtype of 15. Once the eternal version is there, it'll automatically work :)

**Comment by CrimsonCube** [comment]
Done.
