### ISSUE TITLE
[Passive] Gasoline juicebox

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#24]
Tez:
> Tears up, damage down, range down
> 
> Tears are replaced by flames, similar to the blue candle item

dedChar:
### Code
- [x] Stat Changes
- [x] Replace tears with fire
- [x] Synergies with:
   - [x] Red Candle: Fires don't disappear after some time   
    - [x] Blue Candle ("The Candle" ingame): Homing?   
    - [x] ~~Black Candle: ???~~  
    - [x] Ludovico
- [x] Add to Normal (?) Pool
### Art
- [x] Collectible Sprite: A red canister with a straw?
- [x] Costume: gasoline around isaacs mouth
- [x] Note Sprite

**Comment by dedChar** [comment]
@ProbablyTez https://youtu.be/SZBoOzppZDw

**Comment by ProbablyTez** [comment]
Looks great, good job!

**Comment by dedChar** [comment]
From the looks of it it's pretty much done, but I was thinking about adding synergies with the 3 different candle items. For the red candle I thought that the fires that are shot don't disappear, and for the blue candle it would turn the fires blue and add a homing effect. I have no ideas for the black candle though

**Comment by ProbablyTez** [comment]
That could be fun, and more synergy is always better ^^
