### ISSUE TITLE
[Active] The Way

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#249]
### Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Giant book

**Comment by Elkopolo** [comment]
![the way](https://cloud.githubusercontent.com/assets/24684546/23630569/a0d33d20-0289-11e7-837d-9c802497ec5a.png)

does this work?

**Comment by ProbablyTez** [comment]
It does 😄

**Comment by mtblox** [comment]
http://i.imgur.com/eSg88rc.png
http://i.imgur.com/EKY1QRo.png

Sprites are done.

**Comment by mtblox** [comment]
http://i.imgur.com/O7RuU6Z.png

giant book is done as well

although elko insists that the book needs to be closed :(
