### ISSUE TITLE
[Passive] Shutter

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#255]
Tears way up
Player no longer shoot in the 4 cardinal directions
Instead, shoots following a vector, controlled by the shooting joystick

Ex: Vector is init to be vertical, so the player shoots up. If he presses left, Vector rotates until it's horizontal, effectively sweeping the top left part of the room

**Comment by mtblox** [comment]
Shutter (from Shutterstock)
'Vector tears'
