### ISSUE TITLE
[Passive] Gold Man

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#257]
### Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Costume Sprite?
### Code
- [x] Bug : #282

**Comment by Elkopolo** [comment]
![the way](https://cloud.githubusercontent.com/assets/24684546/23630521/72278580-0289-11e7-8555-c3a281501a3f.png)

does this work?

**Comment by dedChar** [comment]
Wrong item :P

**Comment by mtblox** [comment]
http://i.imgur.com/EzPIGvo.png
http://i.imgur.com/A5RiVd7.png
http://i.imgur.com/kITPxXp.png

Sprites are done. I just recolored the <3 costume and added a bit of shading for the costume.
