### ISSUE TITLE
require() rumored to work now

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#258]
According to [a thread on reddit](https://reddit.com/r/themoddingofisaac/comments/5whavb/it_seem_require_is_now_acutally_working_without/) from a few days ago, `require()` now works without `--luadebug`. Not sure if this is true, but I can't test it because I'm not at home and don't know when I'll be back. 
To test this, you'd have to comment out the `Include()` function at the beginning of main and then replace every `Include(something.lua)` call with `require(something)`.

Would be great if it worked

**Comment by ProbablyTez** [comment]
On it

**Comment by ProbablyTez** [comment]
It works, yaaay!
However, for some reason we now get +3 tear delay on new runs
