### ISSUE TITLE
[Bug] Player get +3 tear delay on new run

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#259]
Appeared after switching to require()

**Comment by dedChar** [comment]
Hmmm that's odd.
Do the logs say anything?
Maybe delete the save.dat....

**Comment by ProbablyTez** [comment]
Fixed it! Item The Way had a typo!
However fixing it created another bug, programming yay

**Comment by dedChar** [comment]
Damn it! xD
