### ISSUE TITLE
Cocoons

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#262]
- **Spider Cocoon**
     - Immobile
     - Spawn spiders upon taking damage
     - Spawns a spider related entity on death
- **Chasing Cocoon**
     - Two phases : 
          - Asleep
               - Immobile
               - Upon taking damage, awakens
          - Awake
               - Chases the player
               - Occasionally spawns spiders
- **Shooting Cocoon**
     - Immobile
     - Fires tears like the boil monster, leaving slowing creep
     - On death, fires a last volley and leave slowing creep

Note : We probably can just program a new entity as a base of the cocoon ai. The variant of the cocoon then dictates which type of cocoon it is.

**Comment by ProbablyTez** [comment]
Good idea, will make it easier to manage Types

**Comment by CrimsonCube** [comment]
Note, just in case: function ThrowSpider() doesn't work, so don't try to use that.

**Comment by dedChar** [comment]
I tend to use `Isaac.Spawn()` for most things anyway
