### ISSUE TITLE
[Passive] Cashew Milk

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#263]
Every X seconds at random, raises or tear Delay and Damage greatly

Effectively alternating between Polyphemus and Soymilk

Treasure pool

**Comment by mtblox** [comment]
What if it constantly, somewhat slowly transitioned between high damage, high tear delay and low damage, low tear delay?

**Comment by dedChar** [comment]
Yeah I think a smooth transition like that would be nice

**Comment by ProbablyTez** [comment]
Yup, great idea!
