### ISSUE TITLE
Delusion

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#264]
So, I shared this idea with Tez and he thought it was interesting, so I am going to post it here so that it can be reviewed. Delusions are basically the enemy form of Delirium, changing into random delirious versions of enemies found on the floor. It is treated like a champion enemy, but it is a very rare variation.

In its standard form, it is a small, floating, dripping ball of white sludge, similar to Delirium except it appears to be melting. This aesthetic is carried over to all enemies it can transform into. However, it is unable to teleport, because that would simply be annoying. Maybe it can shoot out a wave of gray tears every now and again, similar to Delirium.

The enemies it can transform to should be restricted to only a few, to make it easier to program and sprite, and also so that we can select specific enemies whose AIs won't make this enemy ridiculously unfair to fight. It should have plenty of health, and upon killing it, it will always drop any consumables that any other champion enemy is able to drop, or rarely a pedestal item.

**Comment by dedChar** [comment]
Wow that's a really great idea! I really like it! ^^
