### ISSUE TITLE
[Passive] [Active] [Transformation] Tammy's items

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#27]
[Passive] Tammy's body : Reduces life to 3 soul hearts on pickup, grants 9 additional lives. The player respawns with 3 soul hearts.

[Active] Tammy's paw : TBD

[Transformation] Tammy : Grants flight, not sure about other effects yet

**Comment by dedChar** [comment]
Not sure about Tammy's paw because the Converter already does that, but better. Maybe it could do the same as guppy's paw, but with black hearts?

**Comment by ProbablyTez** [comment]
Oh, right, I'll try to find a replacement
Converting Red to black hearts doesnt fit thematically though, Tammy being the holy counterpart to Guppy

**Comment by CrimsonCube** [comment]
Perhaps it could give some strong passive bonuses when hold? Perhaps tears up, chance to fire tears in a circle (similiar to Tammy's Head but without damage bonus) and creep and spikes immunity?

**Comment by ProbablyTez** [comment]
This idea will most likely be pretty popular, no need to do it ourselves
