### ISSUE TITLE
[Boss] Joseph

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#271]
### Art
- [ ] Idle
- [ ] Walking
- [ ] Running (Used when chasing the player)
- [ ] Cough (Used when spawning a fly)
- [ ] Shoot
- [ ] Fart (Pushes the layer away)
### Animation
- [ ] Idle
- [ ] Walking
- [ ] Running (Used when chasing the player)
- [ ] Cough
- [ ] Shoot
- [ ] Fart
### Code
- [ ] Make the fired tears lobe
- [ ] Add some sfx

**Comment by dedChar** [comment]
@MajorWipeout has been pretty silent the past month or so. Maybe someone else of the @AgonyTeam/spriters can do this?

**Comment by MajorWipeout** [comment]
@dedChar Sorry, life got pretty hectic a little bit after I started on this. Things are actually settling now, I should be able to do it.

**Comment by dedChar** [comment]
Oh ok then.
Nice to hear that you're still alive ^^
