### ISSUE TITLE
[Passive] Productive Seizure

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#275]
The player's tears are replaced by a hammer and sickle
On hit, the tears deal damage to every enemy in the room, proportional to how many are in the room (the more enemies, the less damage)

Treasure and devil pool because communism is evil

**Comment by dedChar** [comment]
You really seem to expand on that communism theme, comrade

**Comment by ProbablyTez** [comment]
Blame dugs for asking for communist items! ✊
