### ISSUE TITLE
[Trinket] Bloody Nut

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#276]
Every time the player kills an enemy, there's a chance a very small damage bonus will be granted

**Comment by dedChar** [comment]
Permanent bonus or only per room/level?

**Comment by ProbablyTez** [comment]
Permanent, that's why it's a very very small one, we're talking 0.01 dmg up here,
Could also be a random stat

**Comment by dedChar** [comment]
Nah I think with ups this small we should stick to one stat

**Comment by dedChar** [comment]
I'm not sure about the name
I think it should be something with blood since the mechanic is somehow related to Bloody Lust and Lusty Blood

Maybe "Bursted Vein" or something

**Comment by ProbablyTez** [comment]
Yeah I went with a random name, I'm having trouble coming up with names lately, I agree tho
