### ISSUE TITLE
[Enemy] Mystery Sackhead

### ISSUE THREAD

**Issue by CrimsonCube** [ProbablyTez/Agony#279]
- Mystery Sackhead
     - Like Regular Sackhead but tankier
     - On death spawns Mystery Sack
     - Would be either rare variant or only spawn in some special rooms

**Comment by ProbablyTez** [comment]
Wait a Mystery Sack ? that's super op! Unless you mean a sack pickup, in which case the "level 2" Sackhead is already planned to do!

**Comment by CrimsonCube** [comment]
Yes, I meant this sack http://bindingofisaacrebirth.gamepedia.com/Sacks_(Pickup) :P
Although the idea of being extremely rare but for example dropping a random Sack item isn't that bad tbh.

**Comment by ProbablyTez** [comment]
Well then, "Level 2" Sackhead already does that 😉

**Comment by ProbablyTez** [comment]
Also, an extremely rare sack collectible drop coudl be p nice for the eternal alts of these bad boys 😄
