### ISSUE TITLE
[Reload!] All cards do the effect

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#283]

**Comment by dedChar** [comment]
this makes no sense
why does `Isaac.GetCardIdByName("Reload!")` return -1?

**Comment by ProbablyTez** [comment]
Nicolo pls

**Comment by ProbablyTez** [comment]
For some reason you can't have a "!" in the name, otherwise the id will always be -1
Thanks nocolo

**Comment by dedChar** [comment]
Nice good one, nicalis
