### ISSUE TITLE
Guardian bosses and mini-bosses

### ISSUE THREAD

**Issue by CrimsonCube** [ProbablyTez/Agony#285]
### Bosses
- [ ] Monstro
- [ ] Gemini
- [ ] Larry Jr.
- [ ] Steven
- [ ] Pin
- [ ] Blighted Ovum
- [ ] Fistula Big
- [ ] Fistula Medium
- [ ] Fistula Small
- [ ] The Hollow
- [ ] Dark One
- [ ] The Frail
- [ ] Carrion Queen
- [ ] Peep
- [ ] The Bloat
- [ ] Mask of Infamy
- [ ] Scolex
- [ ] Mama Gurdy
- [ ] Blastocyst Big
- [ ] Blastocyst Medium
- [ ] Blastocyst Small
- [ ] Teratoma Big
- [ ] Teratoma Medium
- [ ] Teratoma Small
- [ ] The Fallen
- [ ] War
- [ ] Conquest
- [ ] The Headless Horseman Head
- [ ] The Headless Horseman Body
### Mini-bosses
- [ ] Envy Big
- [ ] Envy Medium
- [ ] Envy Small
- [ ] Gluttony
- [ ] Wrath
- [ ] Pride
- [ ] Lust
- [ ] Super Envy Big
- [ ] Super Envy Medium
- [ ] Super Envy Small
- [ ] Super Gluttony
- [ ] Super Wrath
- [ ] Super Pride
- [ ] Super Lust
- [ ] Ultra Pride Edmund
- [ ] Ultra Pride Florian
- [ ] Krampus
- [ ] Uriel

**Comment by dedChar** [comment]
It's kinda counterproductive to work on something while it's not even approved ^^

**Comment by CrimsonCube** [comment]
Well, I will probably make it a standalone mod instead anyway, so that's no problem.

**Comment by ProbablyTez** [comment]
I like the idea of guardian bosses, however, now that we have the tools, we may want to do something more interesting than just invincible + cant close doors

Stone fatties are a good example, the added "tired" move is pretty nice
