### ISSUE TITLE
[Consumable] Eternal Consumables

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#292]
Eternal enemies are able to drop eternal consumables, such as hearts, coins, bombs and keys. The value of the eternal consumables is equal to the amount of consumables of the same type on the entire floor, without consuming them.

For example, if there is the eternal bomb, 4 normal bombs and a 1+1 bomb, then you will get 7 bombs from the eternal bomb. The other bombs will be available to pick up as well. This ignores golden bombs as they don't actually give bombs.

**Comment by ProbablyTez** [comment]
I don't think that's possible, fun idea either way

**Comment by mtblox** [comment]
idk, I figured since antibirth did it, it should be possible, but maybe it's because they didn't have to work under a bad API

**Comment by ProbablyTez** [comment]
We coudl track how many pickusp have been picked up this floor, but not how many ar eon the floor rn

**Comment by VortexGames** [comment]
Why would this not be possible to code?
