### ISSUE TITLE
Familiar - Nose Baby

### ISSUE THREAD

**Issue by minichibis** [ProbablyTez/Agony#295]
Familiar, shoots small snot tears, treasure pool (and maybe secret pool?)

**Comment by dedChar** [comment]
I like this idea
Maybe it could sometimes sneeze and do a monsto-style shot of snot tears?

**Comment by minichibis** [comment]
that might be a good idea! Maybe there would only be a couple snot tears and the rest would be green tears that leave creep?

**Comment by dedChar** [comment]
Yes, sure variation is always good

**Comment by minichibis** [comment]
a trinket that made all familiars occasionally shoot a snot tear might also be an option

**Comment by minichibis** [comment]
oops

why even put the close issue button so close and so innocuously near the comment?

**Comment by dedChar** [comment]
yeah I don't know why they did that either, @ProbablyTez hits it all the time too ^^

**Comment by ProbablyTez** [comment]
That sounds fun! 
Also yeah, god damn close button
