### ISSUE TITLE
[Passive] Cashew Milk

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#304]
### Art
- [x] Collectible Sprite
- [x] Note Sprite
- [x] Costume

Idea Card : #263

**Comment by NotNeal** [comment]
![collectibles_cashewmilk](https://cloud.githubusercontent.com/assets/10368805/24336756/694f6f16-1262-11e7-880a-a319df7637d4.png)
![costume_cashewmilk](https://cloud.githubusercontent.com/assets/10368805/24336759/7235b536-1262-11e7-9454-cf91164fd3ab.png)
![deathicon_cashewmilk](https://cloud.githubusercontent.com/assets/10368805/24336765/76858896-1262-11e7-8947-0e322e2e42df.png)
Cashew Milk Sprites
