### ISSUE TITLE
[Passive] Safe Space

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#306]
### Art
- [x] Collectible Sprite
- [x] Costume (player wears a safe on his head ?)
- [x] Note Sprite
- [ ] Safe (It's a chest containing the item stored by Safe Space)
     - [ ] Safe Open anim
     - [ ] Safe Opened Sprite
     - [ ] Safe Closed Sprite

Idea Card : #42

**Comment by mtblox** [comment]
http://i.imgur.com/XeX2qvf.png
http://i.imgur.com/o1Z9lVU.png
http://i.imgur.com/Gz7XGpK.png

Sprites are done.
