### ISSUE TITLE
[Active] Plan B

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#312]
Plan B looks the same as Plan C, but coloured yellow. When used, it will deal 1000 damage to all enemies in the room, and then remove all of Isaac's health except for half a heart, similar to Glass Cannon. When used, it turns into Plan C.

**Comment by ProbablyTez** [comment]
I like the idea of alt plans, however this sounds just like a better glass cannon

**Comment by mtblox** [comment]
It's one-time use and it turns into Plan C. Hardly a better Glass Cannon.
