### ISSUE TITLE
[Transformation] Mister Bean

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#313]
- Requires three bean related items
- Tears have a chance to spawn a random fart on hit

**Comment by ProbablyTez** [comment]
I was thinking more of a transformation to solve the bean issue

**Comment by mtblox** [comment]
Who knows, I just dumped this bad idea because I felt like it.

**Comment by ProbablyTez** [comment]
Bean Items are either active or boolean passives, they don't stack, so having lots of them isnt really useful 😄 

Good job on identifying the design space tho, there def is somethign to be done here
