### ISSUE TITLE
[Active] Vanity

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#319]
### Art
- [x] Collectible Sprite
- [x] Note Sprite

Idea Card : #318

**Comment by NotNeal** [comment]
![collectibles_vanity](https://cloud.githubusercontent.com/assets/10368805/24329521/0e1438ec-11d7-11e7-8df5-45e0241f56fb.png)
![deathicon_vanity](https://cloud.githubusercontent.com/assets/10368805/24329523/1a8f8f9a-11d7-11e7-967e-505670a9785f.png)

Vanity Sprites

**Comment by dedChar** [comment]
Don't close the issue when the sprites aren't uploaded yet

**Comment by NotNeal** [comment]
Sorry about that, didn't know.
