### ISSUE TITLE
[Passive] Toy Hammer

### ISSUE THREAD

**Issue by NotNeal** [ProbablyTez/Agony#323]
Isaac has a chance to fire spinning hammer tears. When an enemy is hit by a hammer tear they become "Bruised" for a few seconds. When an enemy is bruised, they become purple in coloration, and take 4x damage from all sources.

Synergies:
Pause!: If Pause is used, during its duration all enemies take huge amounts of extra damage from hammers. (Stop, hammer time!)

9 Inch Nails: Bruised enemies take extra damage from nails.

Lil' Red Book: All tears are hammers while Lil' Red Book is held. (Sickle item pending)

The Nail: Increased chance for hammers while the nail is held.

**Comment by ProbablyTez** [comment]
Really like the idea! However the easter eggs/synergies may be a bit too powerful
