### ISSUE TITLE
[Passive] Oscillator

### ISSUE THREAD

**Issue by NotNeal** [ProbablyTez/Agony#328]
"Wonky stats"
Causes Damage, Shot Speed, and Tear Rate to oscillate back and forth, gaining or losing 0.01 per millisecond.

**Comment by mtblox** [comment]
that moment when Tech X

**Comment by dedChar** [comment]
I think we already have something like the oscillator in the form of Little Sugar DumDum (#93)

**Comment by NotNeal** [comment]
To be fair LSD is an active item, and it doesn't work in the exact same way.

**Comment by ProbablyTez** [comment]
Hm, I think there is enough space to have one more "constant stat changing" item but this may feel a bit too close to Cashew Milk 

How about changign the frequency, like slightly rerolling the stats every room/enemy killed/things picked up/whatever other event
