### ISSUE TITLE
[Familiar] PCBaby

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#332]
> @NotNeal 

> "Upgradeable Buddy"
> Spawns a baby which fires a technology laser. If the player has any other technology items (Technology 2, Tech.5, Tech 9000, etc.) PCBaby will also gain the effects of those items.

**Comment by ProbablyTez** [comment]
So it's basically a sometimes better robot-baby ? I like the idea of an upgradeable familiar but I'm not sure this is the right way to do it
