### ISSUE TITLE
Flaming Clotty

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#335]
- [x] shots are rotated to a degree between -15 and 15
- [ ]  moves faster
- [x] has a chance to fire a fire instead of a tear

**Comment by dedChar** [comment]
@ProbablyTez should we keep this one, or is it too close to antibirths grilled clotty?

**Comment by ProbablyTez** [comment]
I think we should keep it!
I think we should completely ignore what other mods are doing/did and focus on making the best experience possible, even if I've thought otherwise in the past

**Comment by dedChar** [comment]
Yeah I was thinking the same.
I just woke up to a message on reddit today, asking me if the grilled clotties from Antibirth aren't basically the same.
