### ISSUE TITLE
[Transformation] Big D

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#337]
### Art
- [x] Costume Sprite
- [x] Tear Sprite

Idea Card : #336

**Comment by mtblox** [comment]
http://i.imgur.com/cvpAcQs.png

Costume done, cba with tears yet.

**Comment by mtblox** [comment]
http://i.imgur.com/r2zwLR1.png

Tear effect done.

**Comment by mtblox** [comment]
http://i.imgur.com/84dEPYI.png

Better tears.
