### ISSUE TITLE
[Passive] Soiled Diaper

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#340]
'I can't hold it in any longer...'

Isaac charges up a shot, and when he releases, a barrage of brown tears over a period of 0.5 seconds come out of Isaac's backside, similar to the Mega Fatty brown attacks. Basically Monstro's Lung but in reverse, and over a short period of time as opposed to instantly.

Z A N Y
A
N
Y

**Comment by dedChar** [comment]
sounds zany enough to me
