### ISSUE TITLE
[Passive] Stink Eye

### ISSUE THREAD

**Issue by Floofball** [ProbablyTez/Agony#341]
"What smells?"

Gives a luck based chance to shoot a poop tear. Upon hitting an enemy, has a 1/10 chance of turning it into poop (like Flush!), or a 9/10 chance of applying the "Stinky!" status effect  (enemies run from the afflicted enemy). 

Contributes to the "Oh Crap!" transformation.

- **stinky status effect** : apply fear and poison to nearby monsters

**Comment by ProbablyTez** [comment]
Hm, I like the stinky status effect, but let's change it a bit

**Comment by Floofball** [comment]
All right, any suggestions? I got none aside from the one I came up with so ...

**Comment by ProbablyTez** [comment]
Edited your post to include my suggestion ;)
