### ISSUE TITLE
[Active] How to Leap

### ISSUE THREAD

**Issue by Floofball** [ProbablyTez/Agony#342]
3 (maybe 2?) Charge Item

Upon pressing the spacebar, an Epic Fetus cross-hair is presented which can be moved anywhere in the room. Pressing the spacebar again (to prevent accidentally trapping yourself) will cause Isaac to leap into the air and smash into that point, sending out a shock-wave that damages and destroys all enemies and obstacles in it's wake (think The Adversary's jump attack).

Additionally, unlike How to Jump, Isaac can jump anywhere, even over large gaps.

**Comment by dedChar** [comment]
I like this one! It's a nice alternative to Someone's Shoe

**Comment by ProbablyTez** [comment]
Yeah I think there's enough space left for another mobility active item
