### ISSUE TITLE
Beelzebub

### ISSUE THREAD

**Issue by Floofball** [ProbablyTez/Agony#344]
Beelzebub will be a third floor boss (Depths/Necro/Dank D.) with the appearance of a giant, bloated boom fly which constantly bounces around the room. In a sense, this guy is kind of like a posthumous Baby Plum.

While bouncing, he will stop to perform one of four attacks:
_____________________________________________

- Coughs and spits out two boom flies (mobile)
- Vomits a green Monstro-esque volley of shots that leave poison creep on the ground (mobile)
- Stops instantly and slams his body into the ground, creating a rippling shock-wave that disorients the player for a short period of time (think the Echo Bats from AB-)
- Charges from one diagonal corner to the next, smashing into it and spawning 3 boom flies as well as dislodging rock projectiles.

**Comment by mtblox** [comment]
I'm going to deny this idea for a couple of reasons:

 - It is just a bigger version of an enemy, and that kind of idea is something we should avoid, regardless of whether the main game or other mods do this.
 - There are too many concepts taken from a different mod, it may seem like we're trying to ride on the coattails of a popular mod. Making a posthumous version of a boss from another mod is also kind of bizarre.
