### ISSUE TITLE
[Radioactive Pizza] Random numbers are not loaded correctly

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#346]
I have no idea why this is, but it breaks the stats when restarting the game

**Comment by dedChar** [comment]
@ProbablyTez I assigned you, because after staring at the code for ages, I still have no clue why this is.

**Comment by ProbablyTez** [comment]
I'll have a look at it once I'm done with smoker's lung!

**Comment by ProbablyTez** [comment]
I'm not having any issues, weird.
Here's exactly what I did :
- Give myself the item
- Quit the run
- Quit the game
- Launch the game
- Continued

And it seems to work fine

**Comment by dedChar** [comment]
That's odd.
Yesterday I could observe my stats being wrong after restarting. I even checked the savefile for the variables and they were changed.

**Comment by ProbablyTez** [comment]
Weird, I'll leave the issue open and I'll keep an eye out for weird behaviour

**Comment by dedChar** [comment]
Seems like it's just me and my game doesn't save
