### ISSUE TITLE
["Card"] Repair Wrench

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#347]
- [x] Card Sprite
- [x] Giant Card Sprite?

**Comment by mtblox** [comment]
http://i.imgur.com/9ot0Qev.png
http://i.imgur.com/9OAwUnW.png

Sprites are done.

**Comment by dedChar** [comment]
I just noticed that we can't set the back of the card to be something different.
that's bad.

**Comment by mtblox** [comment]
Maybe have it be a maintenance card.

'Need help? Call Dan: 0-800-FIXIT'

The animation can be kept as well, so that seems like a good idea.
