### ISSUE TITLE
[Passive] Oil Slick

### ISSUE THREAD

**Issue by Floofball** [ProbablyTez/Agony#348]
'Slicky feet!"

-1 Tear Delay, -.5 Speed

Grants a luck based chance for Isaac's tears to become oily tears, which, upon contact with an enemy, inflicts the "Oily!" status effect, which applies Ice Physics to that enemy.

Additionally, Isaac now leaves behind an oily black creep behind him, again applying Ice Physics to any enemies inside.

**Comment by ProbablyTez** [comment]
What do you mean by Ice physics, slippery movements ? Wouldnt that make the enemy less predictable in its movements ?

**Comment by Floofball** [comment]
Yeah. That's exactly what I'm going for. Basically, I see it as a) it's a bit of a situational item, probably one you would only take if you had a high rate of fire (to push them back more easily) and b) more status effects are always great in my books.

Like I said, it could be good or bad depending on the setup you have. If you have, like, Soy Milk for example, the high rate of fire and knockback could keep any of the afflicted enemies subdued, but if you have a low rate of fire or lose track of the enemy, things could get a bit more unpredictable and interesting for the player.

**Comment by mtblox** [comment]
I feel like this idea could work better as Vegetable Oil or something that fits the Isaac theme better.
