### ISSUE TITLE
[Enemy] Sprinkler

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#349]
A gaper that appears in the flooded caves, when Isaac walks in the same x- or y-axis as the enemy, it charges up a blast of water from its mouth, which it releases in the direction Isaac was stood relative to the enemy, similar to the Vis in the depths/womb. Short range water attack. Might be too similar to the water-spitting enemies from Antibirth.

**Comment by Floofball** [comment]
Like you said, it seems a bit too much like the Blurbs from AB-. Maybe instead of spitting out water it could do something similar to Mega Fatty's vomit attack? With water instead of vomit, of course.

**Comment by Anonymous-Koala** [comment]
To make it different enough from the Blurbs, you could give it a reskinned short range brimstone(Somewhat like the Azazer range). This is due to you mentioning a similarity to the Vis, which could work well.
