### ISSUE TITLE
[Card] Pot of Greed

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#352]
'Draw 2 cards.'

When Pot of Greed is used, two more random cards are dropped on the ground. If possible, this card should be rarer than other cards.

**Comment by dedChar** [comment]
But there is the "Ancient Recall" card from the booster pack which draws 3 cards. Wouldn't this just be the same but worse?

**Comment by mtblox** [comment]
it's a meme

Also, there are some things that will be outright better than others. Besides, since it is a card, it effectively increases the chance that you get a card that will give you more cards.

**Comment by ProbablyTez** [comment]
Hm, could actually work, but i'd call it something like "Slightly less ancient recall" for maximum meme efficiency

**Comment by CrimsonCube** [comment]
bad meme
