### ISSUE TITLE
[Card] Pot of Duality

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#354]
'Draw 3, choose 1.'

When used, Pot of Duality spawns 3 pedestal items, which Isaac can then choose 1 from. The other 2 then vanish once an item is picked.

**Comment by ProbablyTez** [comment]
Actually I had a similar idea, but it was for an active item. Having it as a card may be too powerful

**Comment by dedChar** [comment]
To me it seems like an active item version of this would be more powerful than the card one, because a card is one time use and an active usually isn't.

**Comment by ProbablyTez** [comment]
Oh I mean yeah, it'd be a one time use active ofc

**Comment by dedChar** [comment]
hmm
I think it would be better suited as a rare card. Doesn't clutter up actives with one-time use items that way.

**Comment by CrimsonCube** [comment]
yet another bad MEME
