### ISSUE TITLE
[Passive] Heart Transplant

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#356]
'Heart failure.'

When Isaac completes all of a floor's normal rooms, he will gain two red heart containers. When Isaac begins to move to the next floor, he will lose a red heart container. The effect cannot take away any blue or black hearts, so if Isaac has no red heart containers, the effect will not occur. If Isaac gains a red heart container by an eternal heart, this red heart container will not be deleted, as the effect of the item will occur before the eternal heart becomes a red heart container.

**Comment by ProbablyTez** [comment]
Wow that was very complex, this would be a very confusing item

**Comment by dedChar** [comment]
So this basically does this:
* -1 red heart container when entering new level
* +2 red heart containers when all rooms explored
right?

**Comment by mtblox** [comment]
Basically. The rest of it can be ignored, it was just for coverage of any holes
