### ISSUE TITLE
[Active] The Root of Anger

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#359]
### Art
- [x] Collectible Sprite
- [x] Rooted Costume Sprite (Should have some roots holdign down the player or whatever)
- [x] Note Sprite

Idea Card : #357

**Comment by mtblox** [comment]
http://i.imgur.com/Ou4Re2F.png
http://i.imgur.com/fVEpJqR.png
http://i.imgur.com/ye16irV.png

Sprites are done. I even animated the costume.
