### ISSUE TITLE
[Enemy] Boney in Shining Armour

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#362]
An enemy that can be found in the Necropolis, the Boney in Shining Armour is a tough enemy that wears a suit of armour and wields a hefty sword. If Isaac walks close to the Boney in Shining Armour, it will swing its sword down towards Isaac, creating a tremor where it lands, and releasing a wave of 5 bones outwards. The Boney in Shining Armour travels slowly, but it is impervious from the front, and will always be facing Isaac whilst moving. The only way to reach its back is to force it to swing, then move behind and shoot it whilst it is vulnerable. Can be treated like a mini-boss.

**Comment by dedChar** [comment]
I don't think armor fits the game that well
