### ISSUE TITLE
[Enemy] Hunchbone

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#363]
An enemy that is primarily found in the Necropolis, the Hunchbone is a Boney that has a large mass of skulls atop its neck, and struggles to keep the weight up. The Hunchbone may topple over after a short period of time, releasing a barrage of bones towards Isaac as well as spawning several Boneys. If Isaac kills the Hunchbone before it falls over, it will spawn less Boneys and will not release bones. The Hunchbone travels fairly slowly and with a stagger to its movement.

**Comment by ProbablyTez** [comment]
I like the falling over part!
