### ISSUE TITLE
[Passive] Eggbeater

### ISSUE THREAD

**Issue by minichibis** [ProbablyTez/Agony#364]
Effect - Significant tears and range up, minor shot speed up. Tears deviate wildly from their path, twisting and turning at arbitrary angles that are unique to each shot.

Appearance - Isaac has an eggbeater implanted in his skull. When firing, Isaac's eyes do not close, instead opting to rattle around as the eggbeater blends inside of his head.

**Comment by ProbablyTez** [comment]
Ooh I like it !
