### ISSUE TITLE
[Passive] Nut Milk

### ISSUE THREAD

**Issue by minichibis** [ProbablyTez/Agony#366]
"Spurt shot"

Effect - Tears down. Isaac now spurts a assault rifle-esque burst of tears that come out quickly and at varied angles. This differs from cursed eye in that its not a charge shot, rather affecting your tears passively. For example, if you got cursed eye, each cursed eye tear would be followed by a burst of tears, making that a very effective synergy indeed.

Appearance - Isaac just drank a glass of ...god I am so sorry

**Comment by ProbablyTez** [comment]
Changed the theme because it's a tiny bit too far/direct for Isaac imo
