### ISSUE TITLE
[Passive] Nut Milk

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#377]
### Art
- [ ] Costume Sprite
- [ ] Collectible Sprite
- [ ] Note Sprite

Idea Card : #366

**Comment by Floofball** [comment]
Hey, do you have any idea where I can get the sprite sheet for the Charging attack costume (Chocolate Milk's, specifically)?

**Comment by Floofball** [comment]
Duh, forget what I said. Just reread the note card lol.

**Comment by Floofball** [comment]
Collectible: http://imgur.com/a/AZ7so
Note: http://imgur.com/a/AmGSP
Costume: http://imgur.com/a/XlLgK
