### ISSUE TITLE
[Passive] Hungry Pumpkin

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#379]
'I am very hungry!'

Isaac's head moves down to his body, so his legs come out from his neck, and his arms are on the sides of his head. Isaac will demand an enemy in a thought bubble randomly in a room, maybe once every 6 rooms with enemies in. If Isaac makes contact with the enemy, he will consume that enemy, restoring 1 red heart and dropping a few random consumables. This only occurs once in a room, Isaac cannot consume multiple of the same enemy in one room.

**Comment by Floofball** [comment]
Don't really get the pumpkin (or costume) part, but it's a pretty neat idea. I think it could work better as like, 'Wendigo's Curse/whatever". Could be a Devil Deal item maybe?

**Comment by mtblox** [comment]
https://www.youtube.com/watch?v=moGGInxjdBg

This is what it's referencing.

**Comment by Floofball** [comment]
@mtblox Huh. Well. That was certainly ... interesting.
