### ISSUE TITLE
[Enemy] Squire

### ISSUE THREAD

**Issue by minichibis** [ProbablyTez/Agony#385]
This foe runs at you in a pattern similar to lust, but slower. However, it constantly slashes a weapon in front of it that deflects bullets shot into it, making it so you cant hit it. If you move at a different angle than the weapon, it slowly changes the angle of the weapon, meaning that you have to run behind it and hit it.

basically like a knight, but with "behind" being more fluid.

**Comment by ProbablyTez** [comment]
So basically a knight with a bigger weakspot that follows you freely

I think it coudl work, but be careful witht he sprite, I feel like it'd be easy to screw this one up and just make a boring knight! :smile:

**Comment by minichibis** [comment]
oh ive got something in mind...

**Comment by Anonymous-Koala** [comment]
Denying this for now. The more you think about it and the scenarios it can be involved in, the more unfun it becomes. Whippers with Lust AI where they angle themselves to deflect you? That's Stony level.
