### ISSUE TITLE
[Character] Enemy death based character

### ISSUE THREAD

**Issue by minichibis** [ProbablyTez/Agony#387]
This character would start with lower damage, higher speed, higher luck, and 2 special things

1. A book that makes enemies do special effects on death.
Examples: explode, petrify nearby enemies, scare nearby enemies, leave creep, leave fire.

2. A trinket that lets them see the health of one enemy, the one last hit.

The character's whole gameplay loop would be killing enemies strategically and using their effects to make up for the characters poor damage.

**Comment by ProbablyTez** [comment]
Love the trinket, a spidermod trinket soudn sliek somethgin that shoudl alreaady exist.

I'm not sure if this character would work though. I think new characters should be more than just "Start with X item", however interestign the item(s) may be. 


Kinda like the item idea though, I don't think it's great right noiw, but I think there's soem potential in there

**Comment by Anonymous-Koala** [comment]
You could go with an approach somewhat similar to how Bethanny and Lilith work. They're not bound to their spacebar items, but on them they have some special tricks(Lilith gets Cambion Conception and Incubus from the get-go which goes VERY well with the item, Beth is the only one able to spawn the other flame types other than blue). Could have some special effects of enemies' deaths happen only with this character.
