### ISSUE TITLE
[Passive] Job reference item too tired to come up with a good name, dont use this as the actual name guys srlsy

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#389]
All stats up

Grants a small all stats up whenever the player skips a devil deal.

Item is removed if the player takes a devil deal.

**Comment by NotNeal** [comment]
Chastity Belt?

**Comment by nick5435** [comment]
<table>
<tr>
<td>Item name: </td><td>Southern Baptist</td></tr>
<tr>
<td>
Description:</td><td>  <img src="https://vignette1.wikia.nocookie.net/starpolar/images/6/6b/Notime.jpg/revision/latest?cb=20150225125846" width="200"/></td></tr></table>
