### ISSUE TITLE
[Familiar] Hungry Jack

### ISSUE THREAD

**Issue by mtblox** [ProbablyTez/Agony#400]
Somewhat of a continuation of the Hungry Pumpkin idea, which I've now scrapped.

'He's very hungry.'

A familiar that follows Isaac, designed like a carved pumpkin with a wide, jagged mouth. It will request a consumable, and if it eats the consumable, it will open its mouth, the consumable will fall in, and if it consumes 3 consumables, it will spawn a random reward, which can be 3+ random consumables, with equal chance of each consumable spawning (not including cards, pills and runes), two chests, or rarely a pedestal item. (eg. 80% 3+ consumables, 15% two chests, 5% pedestal item). If it bumps into a consumable it does not want, it will push the consumable to the side.

I understand that this is an item and we should be staying away from these ideas,  and it's hypocritical of me to enforce that idea and then make an item idea myself, but it was on my mind and I wanted to put it down. **(WE'RE NOT! We only should have a higher standard, keep the ideas coming guys!)**

**Comment by Floofball** [comment]
Wait, we're being discouraged from item ideas? Darn. and I just posted a really good one ...

Good idea, though. It seems more fitting than the Hungry Pumpkin.

**Comment by ProbablyTez** [comment]
Hey, we're not discouraging any kind of ideas, we only raised the standard! 😉 

Regarding this familiar though, if I got this correctly, it's a picky bumbo ? Hm, I'm not sure about this one
