### ISSUE TITLE
[Pickup] Half Soul Half Red Hearts

### ISSUE THREAD

**Issue by VortexGames** [ProbablyTez/Agony#405]
Do NOT function like the ones that already exist. 

If your red health is full, you will only take the soul part of the heart and the heart will become a half red heart. Drops rarely in place of red hearts, and will generally help against new, harder things like eternals.

**Comment by Anonymous-Koala** [comment]
It's been done too much/too close to what has been done already in remix and ab+.

**Comment by dedChar** [comment]
I don't think it would be a good idea to have Half Soul Half Red Hearts if the game already has a different version of them
