### ISSUE TITLE
[Passive] Meat Hook

### ISSUE THREAD

**Issue by Floofball** [ProbablyTez/Agony#410]
"Just a little meat off the top!"

Pools: Devil, Curse Room, Secret Room

Meat Hook grants the player a large, bloodied iron hook which acts as an independent melee weapon and replaces Isaac's tears. To attack with the meat hook, the arrow keys must be held down and then released, but rather than throwing it like Mom's Knife, it will instead swing in a large arc, piercing all enemies caught inside. The longer the key is held down, the larger the arc's range.

Very quick swings of the hook can also be performed, but will only swing in small arcs and deal little damage (about half) of Isaac's current dmg stat.

Additionally, upon killing several enemies (3 or more) at once with a hook swing, Isaac has a chance of gaining a small, temporary damage and speed buff which can last between rooms, but only for a few seconds (this buff cannot be stacked). However, the buff can be prolonged if multiple enemies are combo'ed again.

**Comment by Anonymous-Koala** [comment]
I like it. Item ideas are still something I think we shouldn't focus on but this is a quality example of one.
