### ISSUE TITLE
[Trinket] Broken Spike - Curse Room Immunity

### ISSUE THREAD

**Issue by CrimsonCube** [ProbablyTez/Agony#412]
Pretty self explainatory. Would look like a spike from curse room door, although I guess slightly larger and broken. I have the code pretty much ready.

**Comment by dedChar** [comment]
Sounds like a nice trinket, but on second thought it may be OP considering you could get angel keys, soul hearts, coins and teleport to dark room for free.

**Comment by CrimsonCube** [comment]
Hmm you are right. It could also work as an item, although it would also need to have something like a damage up, because just curse room door immunity is a bit to situational.

**Comment by Floofball** [comment]
6
