### ISSUE TITLE
[Passive] Eye of Providence

### ISSUE THREAD

**Issue by Floofball** [ProbablyTez/Agony#414]
"When gravity falls and earth becomes sky ..."

Item Pool: Secret room, I AM ERROR room

On pickup, Eye of Providence will reverse gravity (all enemies, including the player, can now fly) and adds the "Anti-Gravity" effect to both the player's and enemies' tears. Additionally, it grants the player full mapping but at the cost of a permanent Curse of the Maze as well as the same map effect in the 'April's Fool' challenge.

**Comment by dedChar** [comment]
What is the map effect in the April fool's challenge? Not sure if we can do that. 
Also I think anti gravity on the enemies shots would just make them delayed shots.

**Comment by Floofball** [comment]
The effect is basically that the room you're in doesn't actually match what you see on the map, although the map itself is still accurate.
