### ISSUE TITLE
[Passive] Safe Space

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#42]
- **Removes random Item**
- **Grants removed Item on next run**
- **Shop pool**
- **Literally a Safe**

**Comment by ProbablyTez** [comment]
I like it though it might be a little overpowered (break the game, get the noose, then play lost for easy unlocks) maybe limit it in some way, like only the last item you picked up is carried over ?

**Comment by dedChar** [comment]
Yeah you're right. Didn't think of that. I think the last 2 items would be a good amount.

**Comment by ProbablyTez** [comment]
Yeah, testing will reveal its actual strength anyway, good idea nonetheless

**Comment by ProbablyTez** [comment]
How about it guaranteed gives the current active item to the next run ?
The fact that it ends the current run makes it so that its effect must be pretty strong,
but if the effect is too strong it just gives a free run, which isnt that fun
Tough item to balance!

**Comment by dedChar** [comment]
That sounds good too, I would then change the name though.
Maybe "The Safe" as the name and "Protect your precious item from the evil!" as a description.

**Comment by dedChar** [comment]
God damnit tez you always spook me with your ghost edits
