### ISSUE TITLE
[Enemy] Monstros Fly

### ISSUE THREAD

**Issue by ghost** [ProbablyTez/Agony#424]
A fly which flies in your direction with small charges on every wingstrike and spits out tears similar to Monstro.
I have already created the Sprites and Animation including Events.
![monstrosfly](https://cloud.githubusercontent.com/assets/16121320/25551816/44013ad0-2c8b-11e7-91e4-c595268ca925.png)
[monstrosfly.zip](https://github.com/AgonyTeam/Agony/files/965813/monstrosfly.zip)

Could code it myself but i cant figure out how to change `Entity_Projectile`s Stats. (Height, FallingSpeed, Flags etc.)

**Comment by Anonymous-Koala** [comment]
I really dislike the idea of a monstro fly. Seems too ridiculous and out of place, to pluck Monstro of all enemies, onto a fly. Besides, it'll be too similar to minstros.

**Comment by dedChar** [comment]
Not sure about this either, kinda dislike the idea of Monstro-ifying enemies.
If you want some help with the code, I'll be glad to help out. You can find me on the agony discord if you want some help.
