### ISSUE TITLE
[Passive] tear control (needs better name)

### ISSUE THREAD

**Issue by DirtShadow** [ProbablyTez/Agony#437]
Effect: Makes it so that if you change shooting direction your already shot tears go that way. 
Visual representation (example): https://imgur.com/gallery/uibuA 
Video of the item https://youtu.be/6QoqSg4YZDE https://youtu.be/JCy0LhP-xOM
Makes it so that you can snipe enemies around corners.

**Comment by Floofball** [comment]
Eye of the Occult from Antibirth already exists and is very similar.

**Comment by Floofball** [comment]
Closing due to Blind Faith.
