### ISSUE TITLE
[Passive] The Big Rock

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#45]
Art
- [x] Collectible Sprite 
- [x] Costume
- [x] Note Sprite

Code
- [x] One in ten times the small rock spawns, replace it by the big rock

**Comment by Elkopolo** [comment]
![large rock](https://cloud.githubusercontent.com/assets/24684546/23677832/bdb070e0-034f-11e7-98bd-c7216532c977.png)
![large rock costume](https://cloud.githubusercontent.com/assets/24684546/23677833/bdb48824-034f-11e7-84eb-7f735937aaaa.png)

**Comment by Elkopolo** [comment]
![death items mod](https://cloud.githubusercontent.com/assets/24684546/23677877/d67d235c-034f-11e7-8250-0eafe0bcac06.png)

should i keep the custom death items separate?

**Comment by dedChar** [comment]
Yeah they should actually be seperated into single files
