### ISSUE TITLE
[Active] Sunken Remote

### ISSUE THREAD

**Issue by ghost** [ProbablyTez/Agony#456]
- Pools: Item (+ Garbage Items?)

- 1 Room Charge

On use, pauses or reverses all enemy projectiles on screen.

Prototype (with placeholder art):
https://cdn.discordapp.com/attachments/287606150424166400/310594812820848640/Soaked_Remote.gif

Final Design by @Floofball 
http://imgur.com/a/ySzM1

**Comment by Anonymous-Koala** [comment]
Removing this, the booster pack introduces an item which does exactly this, and more.
