### ISSUE TITLE
[Passive] Optimism

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#46]
Raises the weakest stat
treasure pool

**Comment by ProbablyTez** [comment]
Just realized this item already exists in Antibirth, oops

**Comment by mtblox** [comment]
Hey, that's never stopped Nicalis from making AB+

**Comment by ProbablyTez** [comment]
We're professionals though :^)

**Comment by dedChar** [comment]
Ooooohhhh shots fired xD
