### ISSUE TITLE
[eNeMY FamiLY] This is just a test for the label bot. Ignore pls, unless you're a bot.

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#472]
01010100 01101000 01100101 00100000 01001011 01110010 01100001 01100010 01100010 01111001 00100000 01010000 01100001 01110100 01110100 01111001 00100000 01100011 01101111 01101110 01110100 01100001 01101001 01101110 01110011 00100000 01100010 01101111 01110100 01101000 00100000 01110100 01101000 01100101 00100000 01110100 01101111 01110000 00100000 01100010 01110101 01101110 00100000 01100001 01101110 01100100 00100000 01110100 01101000 01100101 00100000 01100010 01101111 01110100 01110100 01101111 01101101 00100000 01100010 01110101 01101110 00101100 00100000 01110111 01101001 01110100 01101000 00100000 01110100 01101000 01100101 00100000 01110100 01101111 01110000 00100000 01100010 01110101 01101110 00100000 01100011 01101111 01101110 01110100 01100001 01101001 01101110 01101001 01101110 01100111 00100000 01110011 01100101 01110011 01100001 01101101 01100101 00100000 01110011 01100101 01100101 01100100 01110011 00101110 00100000 01001001 01110100 00100000 01100001 01101100 01110011 01101111 00100000 01100011 01101111 01101110 01110100 01100001 01101001 01101110 01110011 00100000 01110011 01100101 01100001 00100000 01100011 01101000 01100101 01100101 01110011 01100101 00101100 00100000 01110011 01100101 01100001 00100000 01101100 01100101 01110100 01110100 01110101 01100011 01100101 00101100 00100000 01110011 01100101 01100001 00100000 01110100 01101111 01101101 01100001 01110100 01101111 00101100 00100000 01110000 01101001 01100011 01101011 01101100 01100101 01110011 00101100 00100000 01101011 01100101 01110100 01100011 01101000 01110101 01110000 00101100 00100000 01101101 01110101 01110011 01110100 01100001 01110010 01100100 00101100 00100000 01101101 01100001 01111001 01101111 01101110 01101110 01100001 01101001 01110011 01100101 00101100 00100000 01100001 01101110 01100100 00100000 01110011 01100101 01100001 00100000 01101111 01101110 01101001 01101111 01101110 01110011 00101100 00100000 01100001 01101100 01101100 00100000 01101111 01100110 00100000 01110111 01101000 01101001 01100011 01101000 00100000 01100011 01100001 01101110 00100000 01100010 01100101 00100000 01110011 01100101 01100101 01101110 00100000 01110111 01101000 01100101 01101110 00100000 01100001 00100000 01001011 01110010 01100001 01100010 01100010 01111001 00100000 01010000 01100001 01110100 01110100 01111001 00100000 01101001 01110011 00100000 01100010 01100101 01101001 01101110 01100111 00100000 01101101 01100001 01100100 01100101 00100000 00101000 01100001 01101110 01100100 00100000 01100001 01110011 00100000 01110111 01100101 01101100 01101100 00100000 01100011 01101111 01110010 01110010 01100101 01101100 01100001 01110100 01100101 00100000 01110100 01101111 00100000 01110100 01101000 01100101 00100000 01101001 01101110 01100111 01110010 01100101 01100100 01101001 01100101 01101110 01110100 01110011 00100000 01110100 01101000 01100001 01110100 00100000 01100011 01100001 01101110 00100000 01100010 01100101 00100000 01100110 01101111 01110101 01101110 01100100 00100000 01101001 01101110 00100000 01101110 01101111 01110010 01101101 01100001 01101100 00100000 01100010 01110101 01110010 01100111 01100101 01110010 01110011 00101001 00101110 00100000 01000001 01110011 00100000 01110111 01100101 01101100 01101100 00100000 01100001 01110011 00100000 01100001 01101100 01101100 00100000 01101111 01100110 00100000 01110100 01101000 01101111 01110011 01100101 00100000 01101001 01101110 01100111 01110010 01100101 01100100 01101001 01100101 01101110 01110100 01110011 00100000 01101001 01110011 00100000 01110100 01101000 01100101 00100000 01110000 01100001 01110100 01110100 01111001 00100000 01100001 01101110 01100100 00100000 01110011 01100101 01100011 01110010 01100101 01110100 00100000 01110011 01100001 01110101 01100011 01100101 00101100 00100000 01100010 01101111 01110100 01101000 00100000 01101111 01100110 00100000 01110111 01101000 01101001 01100011 01101000 00100000 01101000 01100001 01110110 01100101 00100000 01110101 01101110 01101011 01101110 01101111 01110111 01101110 00100000 01101001 01101110 01100111 01110010 01100101 01100100 01101001 01100101 01101110 01110100 01110011 00101100 00100000 01110000 01100001 01110010 01110100 01101001 01100011 01110101 01101100 01100001 01110010 01101100 01111001 00100000 01110100 01101000 01100101 00100000 01110000 01100001 01110100 01110100 01111001 00101110 00001101 00001010 00001101 00001010 01010100 01101000 01100101 00100000 01110000 01100001 01110100 01110100 01111001 00100000 01100001 01101110 01100100 00100000 01110100 01101000 01100101 00100000 01101111 01110100 01101000 01100101 01110010 00100000 01110011 01100101 01100011 01110010 01100101 01110100 00100000 01101001 01101110 01100111 01110010 01100101 01100100 01101001 01100101 01101110 01110100 01110011 00100000 01100001 01110010 01100101 00100000 01101111 01100110 00100000 01110100 01101000 01100101 00100000 01101101 01101111 01110011 01110100 00100000 01110000 01101111 01101001 01101110 01110100 00100000 01101111 01100110 00100000 01101001 01101110 01110100 01100101 01110010 01100101 01110011 01110100 00101110 00100000 01010011 01101001 01101110 01100011 01100101 00100000 01110100 01101000 01100101 01110010 01100101 00100000 01101001 01110011 00100000 01101110 01101111 00100000 01101101 01100101 01101110 01110100 01101001 01101111 01101110 00100000 01101111 01100110 00100000 01110111 01101000 01100101 01110010 01100101 00100000 01110100 01101000 01100101 00100000 01110000 01100001 01110100 01110100 01111001 00100000 01101101 01101001 01100111 01101000 01110100 00100000 01101000 01100001 01110110 01100101 00100000 01100011 01101111 01101101 01100101 00100000 01100110 01110010 01101111 01101101 00100000 01101110 01101111 01110010 00100000 01110111 01100001 01110011 00100000 01110100 01101000 01100101 01110010 01100101 00100000 01110110 01100101 01110010 01111001 00100000 01101100 01101001 01110100 01110100 01101100 01100101 00100000 01101101 01100101 01101110 01110100 01101001 01101111 01101110 00100000 01101111 01100110 00100000 01110011 01101111 01101101 01100101 00100000 01101111 01100110 00100000 01110100 01101000 01100101 00100000 01110100 01101000 01101001 01101110 01100111 01110011 00100000 01110100 01101000 01100001 01110100 00100000 01100001 01110010 01100101 00100000 01100001 01101100 01110011 01101111 00100000 01101001 01101110 00100000 01100001 00100000 01001011 01110010 01100001 01100010 01100010 01111001 00100000 01010000 01100001 01110100 01110100 01111001 00101100 00100000 01110100 01101000 01100101 00100000 01101001 01101110 01100111 01110010 01100101 01100100 01101001 01100101 01101110 01110100 01110011 00100000 01101111 01100110 00100000 01110100 01101000 01100101 00100000 01110000 01100001 01110100 01110100 01111001 00100000 01100001 01101110 01100100 00100000 01101111 01110100 01101000 01100101 01110010 00100000 01110011 01100101 01100011 01110010 01100101 01110100 00100000 01101001 01101110 01100111 01110010 01100101 01100100 01101001 01100101 01101110 01110100 01110011 00100000 01101111 01100110 00100000 01110100 01101000 01100101 00100000 01001011 01110010 01100001 01100010 01100010 01111001 00100000 01010000 01100001 01110100 01110100 01111001 00100000 01110010 01100101 01101101 01100001 01101001 01101110 00100000 01100001 00100000 01101101 01111001 01110011 01110100 01100101 01110010 01111001 00101110

**Comment by dedChar** [comment]
NO BAD @dedBot, BAD!

**Comment by ghost** [comment]
Do you have treats for it when it does things right?

**Comment by dedChar** [comment]
Yeah it'll get more work as a treat! Robots love that!

**Comment by ghost** [comment]
Noice

**Comment by dedChar** [comment]
god damnit @dedBot

**Comment by dedChar** [comment]
ayy he works finally
