### ISSUE TITLE
[Eternal]  Boom Fly

### ISSUE THREAD

**Issue by ghost** [ProbablyTez/Agony#485]
### Art
- [x] [Sprite](https://github.com/AgonyTeam/Agony/blob/ANewKindOfPain/resources/gfx/Monsters/Eternals/Boom%20Fly/main.png)

### Misc
- [x] Remove Color-Offset [here](https://github.com/AgonyTeam/Agony/blob/ANewKindOfPain/code/Monsters/Eternals/BoomFly.lua#L19) after Sprite is done

Idea card: #238

**Comment by Floofball** [comment]
http://imgur.com/a/lmzOM

**Comment by Anonymous-Koala** [comment]
You forgot to link the idea card
