### ISSUE TITLE
[Creep] Stuffed Creep

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#494]
### Art
- [x] Sprite
### Animation
- [x] Attack (the mouth going back to normal after a charge)
- [x] Charge (the 8 states of charge)
- [x] Walk
### Code
- [x] Make movements not smooth
- [x] Add Sounds

###### Idea Card: #395

**Comment by Floofball** [comment]
Done: http://imgur.com/a/1H9zk

**Comment by Floofball** [comment]
Updated sprites: http://imgur.com/a/uIRAM
