### ISSUE TITLE
Basic Guide for Eternal Danger-Values

### ISSUE THREAD

**Issue by ghost** [ProbablyTez/Agony#506]
As of 1.6.2017 the danger values for non-eternals are calculated dynamically like this:
```lua
if enemy:IsVulnerableEnemy() then
	--If Enemy is vulnerable
	danger = enemy.MaxHitPoints + 5
else
	--If Enemy is invincible set danger to 5
	danger = 5
end

if enemy.CollisionDamage == 0 then
	--If the Enemy doesn't damage on touch
	danger = danger * 0.5
end
```

---
Here is a list of non-eternal danger-values for orientation:
```
Fly = 4 (Halved because a Fly doesn't damage you on touch)
Attack Fly = 10
Spider = 11.5
Horf = 15
Small Crazy Long Legs = 17
Crazy Long Legs = 21
(Red/Drowned) Boom Fly = 25
```

Eternals should normally have a higher danger-value than their normal counterparts.
But make it too high and the FairnessSystem will probably never spawn it.

Here is an example for the Eternal Spider.
```lua
Agony:AddEternal(EntityType.ENTITY_SPIDER,0,"Spider",14)
```
I gave it a danger-value which is just 2.5 higher than a normal spider because the Eternal Spider isn't much more dangerous.

Now the Eternal Boom Fly is something else entirely. It is much more dangerous than a normal Boom Fly.
```lua
Agony:AddEternal(EntityType.ENTITY_BOOMFLY,0,"Boom Fly", 34)
```
I gave it a danger-value which is 9 higher than a normal Boom Fly.

---
I will further tweak the FairnessSystem so values will probably change and other factors like floor-type will play a role in the future.

**Comment by dedChar** [comment]
Dude we have a wiki you know

**Comment by dedChar** [comment]
Better put it there

**Comment by dedChar** [comment]
[Moved to wiki](https://github.com/AgonyTeam/Agony/wiki/Room-Fairness-System)
