### ISSUE TITLE
[Card] Lottery ticket

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#51]
Spawns one of the following at random :
Slot Machine
Fortune Teller
Blood Donation Machine
Restock Box
~Donation Machine~ **not possible because mods disable them**

**Comment by dedChar** [comment]
What about the Greed Donation Machine?

**Comment by ProbablyTez** [comment]
I felt like it was a bit redundant, since it's basically the same thing as the Donation machine
I'm not sure if it should include beggars though, or if we should make another card spawn them

**Comment by dedChar** [comment]
I don't think it should contain beggars because that kinda doesn't fit into the "lottery" theme. Besides there already is the Judgement tarot card that spawns them

**Comment by dedChar** [comment]
We can't spawn any donation machines, which would leave us with only 4 slot machines. Everything except the restock box is already spawnable through other cards. What now?

**Comment by ProbablyTez** [comment]
Wait we can't spawn donation machines ? What the hell

**Comment by dedChar** [comment]
Yeah donation machines generally don't appear when mods are enabled

**Comment by ProbablyTez** [comment]
Oh right
