### ISSUE TITLE
Friends ?

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#56]
Little cute babies walking around the room
Aggro monsters
Take damage from all sources
If alive when the room is cleared, spawn a reward

**Comment by dedChar** [comment]
So this is just an Entity that we can put into rooms? Or what if it was a familiar? If the room is cleared 4 (or some other number of) these babies follow the player by floating together in a bubble, or maybe a cocoon. When the player enters a new uncleared room, the bubble/cocoon bursts and the babies start walking around. When the room is cleared or if one of them dies, they go back into their bubble/cocoon.

**Comment by dedChar** [comment]
Sound great nonetheless ^^

**Comment by ProbablyTez** [comment]
I was picturign them as entites we can put in the early stages, but actually we could make both versions ^^
