### ISSUE TITLE
[Gasoline Juicebox] Fires can't destroy poop --> some rooms become undoable

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#58]
Need to make the fires created by the item be able to destroy poop.

**Comment by ProbablyTez** [comment]
I was able to destroy the poops with enough firerate
Also low tear delay + gj is amazingly fun

**Comment by dedChar** [comment]
Hmm.. When I try I can't get the poop to break, even with a firerate as low as 3 :/

**Comment by ProbablyTez** [comment]
I was at 1 teardelay, that might be it
