### ISSUE TITLE
[Passive] Tourette

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#61]
Art
- [x] Collectible Sprite 
- [x] Costume
- [x] Note Sprite

Idea card : #57

**Comment by Elkopolo** [comment]
![tourette](https://cloud.githubusercontent.com/assets/24684546/23677900/eca4fb46-034f-11e7-831f-8095c1e18e13.png)
![tourette costume](https://cloud.githubusercontent.com/assets/24684546/23677901/eca9a8f8-034f-11e7-80cd-da5380b6069e.png)

i used qbert as insperation

![death items mod](https://cloud.githubusercontent.com/assets/24684546/23677910/f3df3f7a-034f-11e7-843a-9ca7696abc03.png)


death item should be at bottom
