### ISSUE TITLE
[Gasoline Juicebox] Ludovico breaks the item and gives you an amazing firetrail

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#62]

**Comment by dedChar** [comment]
Haha that really looks amazing!

**Comment by dedChar** [comment]
Do you think we should make them synergize, so that we would get a controllable fireplace?

**Comment by ProbablyTez** [comment]
That'd be awesome, I think what we'll have to do eventually is set up a list for the most important synergies and hardcode them, just like Nicalis did

**Comment by ProbablyTez** [comment]
An idea for the ludo - gasoline synergy : 
Controllable fireball that leaves behind a small fire trail (like big leaking gasoline tear)

**Comment by dedChar** [comment]
I opened up a new branch called 'Gasoline_Ludo_Syn' and pushed some code to it I wrote like two weeks ago. It doesn't really work the way I want to though. I don't know how to get it to work that we can control a fire instead of a tear when you have ludo and gasolinejb. Maybe you could have a look @ProbablyTez ?

**Comment by ProbablyTez** [comment]
I played around with a controllable fire earlier today, not really functional yet but it might be the way to go

**Comment by ProbablyTez** [comment]
Alright, so now here's how the synergy works : 
   - You control a big ol fire, leaving regular fires behind at random
   - The big fire flies over anything (including walls, gotta fix that)
   - The damage of all fires has been nerfed to a third of the player damage, still really strong

**Comment by dedChar** [comment]
Nice to see you got it working! I didn't know we could get the joystick input directly, but at least now I do :D

Although from a quick look at the code I think the synergy will break if you exit the run, restart the game and the continue it. That would be an easy fix though :P

**Comment by ProbablyTez** [comment]
Yeah the code needs some more work, for some reason I can't get RNG():GetSeed() to work, it always gives back the same number, I'm probably doign somethgn stupid without realizing

**Comment by dedChar** [comment]
That's because RNG():GetSeed() apparently doesn't get the current seed of the game, but the seed of... RNG or something... and it's always the same, unless changed through RNG():SetSeed().

**Comment by dedChar** [comment]
Also if Gasoline Juicebox is removed, the player loses the ability to fire tears until the run is reloaded

**Comment by ProbablyTez** [comment]
Alright so I'm not going crazy, RNG():GetSeed does not return the run seed

**Comment by dedChar** [comment]
I think the main point of this issue is adressed, so I'll close it now
