### ISSUE TITLE
[Active] Someone's Shoe

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#63]
* One Room Charge
* Recharges slowly on its own
* Upon usage the player switches places with a random enemy

**Comment by ProbablyTez** [comment]
Interesting, though maybe swap places with the furthest away enemy makes more sense ?

**Comment by ProbablyTez** [comment]
An idea for a new name : something something shoe related
Like : "Someone's shoe" "Feels weird to walk a mile in those"
