### ISSUE TITLE
[Passive] Magical Chain

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#64]
While held ´, all tears shot are bound together by a chain that also hurts enemies

Very similar to [VertebraK-47 from EtG](https://www.youtube.com/watch?v=iEqs4Q9_9Yo)

**Comment by ProbablyTez** [comment]
I love it! But maybe it should be an item instead ? It sounds really strong, amazing idea either way ^^

**Comment by dedChar** [comment]
Yeah it might actually be better as an item

**Comment by ProbablyTez** [comment]
Changed the name to Overgrown Spine, felt like it was more fitting to Isaac while still referencing EtG ^^
Also the description ("And his music was electric") references Risk of Rain, which also has a chaining item
