### ISSUE TITLE
[Floor] Frozen Depths

### ISSUE THREAD

**Issue by dedChar** [ProbablyTez/Agony#66]
* Everything is slippery
* Frozen Variants of Enemies appear
   * Frozen enemies can shoot ice tears
* Ice Glaciers with Enemies frozen in them
   * player can free them by shooting the glaciers
   * Pickups can also be in a glacier

**Comment by dedChar** [comment]
Floors aren't possible for now though, I think

**Comment by ProbablyTez** [comment]
Yup, as far as I know floors aren't doable but throwing ideas around wont hurt!
How about only having some patches be slippery instead of everything ?  or some room ?
I like the idea of frozen variants, we should expand on that
And glaciers are super cool, it's like a challenge room but you see everything you're going to get beforehand
Nice!

**Comment by ProbablyTez** [comment]
Denied because impossible at the moment, we definitely will look into it whenever it's doable tho

**Comment by dedChar** [comment]
Should be possible pretty soon though. If you look into enums.lua in resources/scripts, you can see a new callback related to level generator :)
Not implemented though I think

**Comment by ProbablyTez** [comment]
Hopefully it's fully functional, new floors would be amazing!
Unique new floor alt really will give a lot of identity to the mod

**Comment by dedChar** [comment]
https://twitter.com/BroskiPlaysYT/status/836981141521444864
Looks like someone has found a way, but he won't tell
New floors too

**Comment by ProbablyTez** [comment]
It could also just be a sarifice room alt couldnt it ? Either way it doesnt seem like the code is available, so no need to worry about it just yet

EDIT: looking at the photo, I realize that there is no HUD or player, so it may not even be implemented yet
