### ISSUE TITLE
[Active] Runestone

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#71]
Art
- [x] [Collectible Sprite](http://i.imgur.com/3VxDBDc.png)
- [x] [Note Sprite](http://i.imgur.com/okTWAKY.png)

**Comment by dedChar** [comment]
Looks good! Same goes for Triplopia #52 , but you might want to actually upload the sprites to the repo ^^

**Comment by ProbablyTez** [comment]
Oh, right, not sure why I didnt think of it earlier
