### ISSUE TITLE
[Passive] Pyramid Head

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#78]
Permanent curse of darkness
Enemies randomly get scared when close to the player
Damage up
Reference to Silent Hill's Pyramid Head
Treasure and Devil Pool

**Comment by ProbablyTez** [comment]
I just learned that Glaucoma has a similar effect, what the hell, I'm sad

**Comment by dedChar** [comment]
Well glaucoma makes the player shoot tears that can make enemies confused. Pyramid Head sounds like a completely different item to that.

**Comment by ProbablyTez** [comment]
I was talking about the permanent curse of darkness effect haha
