### ISSUE TITLE
[Passive] Till Death do us apart

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#79]
Enemies killed have a chance to be revived and charmed permanently
Desc : "Or... Not ?"
Treasure and Devil pool

**Comment by gm-xanther** [comment]
Went ahead and put this one together. The effect scales with luck - if you feel it's too common or too rare, feel free to adjust with the base and multiplier variables at the top of the script! The sprite is a Nicalis-caliber modified recolor, replace as desired ;)

[Til Death Do Us Part.zip](https://github.com/AgonyTeam/Agony/files/736635/Til.Death.Do.Us.Part.zip)

**Comment by dedChar** [comment]
Thanks for the contribution @otherhand42 :)
You might want to consider creating Pull Request next time ^^
