### ISSUE TITLE
[Familiar] Tiny Tiny Horn

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#83]
Follows the player
Occasionally fires a small black orb, similar to Small Horn's
Devil pool

**Comment by dedChar** [comment]
Aaaand someone did it.
https://gfycat.com/QueasyGratefulGonolek

**Comment by ProbablyTez** [comment]
Yeah that's going to happen a lot haha

**Comment by Anonymous-Koala** [comment]
Get rid of this one. Been done in other mods ,sucks in all of them and does the exact same here.
