### ISSUE TITLE
[Active] Pyrite nugget

### ISSUE THREAD

**Issue by ProbablyTez** [ProbablyTez/Agony#90]
One room charge
Spawns a pyrite coin. The coin doesn't do anything when picked up
Treasure and shop pool

**Comment by dedChar** [comment]
Why tho :D

**Comment by ProbablyTez** [comment]
You can reroll those! :D 
It probably should spawn multiple coins at once though

**Comment by dedChar** [comment]
Ah ok that makes sense ^^
